CREATE TABLE IF NOT EXISTS `Items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Item` VARCHAR(200) NOT NULL,
  `Carton_Qty` INT NULL,
  `Price` DOUBLE NULL,
  `Colour` VARCHAR(100) NOT NULL,
  `Size` VARCHAR(100) NULL,
  `Desc` VARCHAR(200) NOT NULL,
  `Weight` DOUBLE NULL,
  `EAN13` VARCHAR(13) NULL,
  `DUN14` VARCHAR(14) NULL,
  `Image_Path` VARCHAR(255) NULL,
  PRIMARY KEY (`id`, `Item`),
  UNIQUE INDEX `Item_UNIQUE` (`Item` ASC) ,
  UNIQUE INDEX `DUN14_UNIQUE` (`DUN14` ASC) ,
  UNIQUE INDEX `Itemscol_UNIQUE` (`Image_Path` ASC) ,
  UNIQUE INDEX `EAN13_UNIQUE` (`EAN13` ASC))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `desc` VARCHAR(1000) NOT NULL,
  `time` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


